worker_processes 2; # по умолчанию 2 процесса
user  nginx;
events {
  worker_connections 1024; #Это директива в nginx, которая указывает сколько одновременных соединений может обрабатывать один рабочий процесс(worker process) - по умолчанию 512   
}
http {
  include /etc/nginx/mime.types; #Nginx понимает - как отдавать разного типа статику
  upstream backend_upstream {
    server backend:5000; 
  }
  include /etc/nginx/conf.d/*.conf; 
}
